function palindromeIndex(s) {
  // create array sArrReverse of s
  const sArrReverse = s.split("").reverse();
  // Write your code here
  if (s === sArrReverse.join("")) {
    return -1;
  }

  // loop through sArr
  for (let i = 0; i < s.length; i++) {
    // put all char of s in array: sArr
    const sArr = s.split("");
    ////  remove each i of sArr
    sArr.splice(i, 1);
    const sArrReverseClone = [...sArrReverse];
    //// create string sNew after removing char
    const sNew = sArr.join("");

    //// find index of the char backward in sArrReverse
    const indexOfCharInsArrReverse = sArrReverseClone.length - 1 - i;
    //// remove  this char out of sArrReverse
    sArrReverseClone.splice(indexOfCharInsArrReverse, 1);

    //// create a string from sArrReverse
    const sReverse = sArrReverseClone.join("");

    // if sArrReverse === sArr => return the char
    if (sNew === sReverse) {
      console.log(i);

      return i;
    }
  }
}

palindromeIndex(
  // "raacecar"
  //   "bsyhvwfuesumsehmytqioswvpcbxyolapfywdxeacyuruybhbwxjmrrmjxwbhbyuruycaexdwyfpaloyxbcpwsoiqtymhesmuseufwvhysb"
  //   "raacecar"
  //racecaar
  "prrmdeykhorwsalkysinbvylgcgiaokrifgolfytvsqqufctxkjbijnonvapmkivrokewlasfskcxowyyiakrpyilyxbmgygxjkuwmpegcheqgdsogdjverkgpnuymbyxovublchqjojptegahpyojlucypdnqclfxijlkqevhoncsuedmftwsoytgchygsheeqrojwlrnbvivanjihibvjvelderylxderrnqffehdnfebqmlypjilovrspqgpvkipabvigflvkryegkdwuoklmcedumuqyfhyhfjpkvnwnmbuahtwxeikjopednxcsfdcmnrwlfvbuaxwhrthyeriskovxoasvdvisnhgveisggppblwapqkkbbiyqismnqvhgdnejxwrfohgaeirvuewvmyoutcjkassfixphuhmmruovfhtaltxysnvophbpatwjrmspwhcqcqmjahjobhpvulmmtnevjchcqarphvglmvwpfgeiqtenfsdbghxplhtdknstjciyxfofmsnfmtutmxvugvmrfhwpwsmjuukuabaovpvijrevpcqxadqgmpxmikvfhgcijcyfrvpdntydyrcyxuhmkiyvuwbdfenoimtdkjgxgiefaigxdonpwmltmpwrvkheadhkpqlvypbyxhadxnswchroyojucsyevjonaajyrmarwcuwpquuamlyduvhpulogdcidojxbmpaonxhescehpfknbudxgthjwpplcnoofpdsnmyiofphkcunwaoguvptnhfpwtgdlmxyyxjqdyxqeuedwujrqalhjswhpgmbskdrimiooifsdlvdhiuakjhtehbtnnxgbbajpjagtfyatxdbiabsjlmosqkggiohjotcatiuckuvkaysaclknabgqloxudfgsbisvtpxemtomuhnwualubtmojmjmtqhvbbruqrygnpsiwghriupjpcyboknkdvgfyacrrexhtrptaxnjudukhvlxhcjkapryswqkbrswlkqlkfwgkussqhqajanjsfklcdxfusdgetuqbtymoshicxilbvwtcjhgmfokyrsfnpvrkxgbsnjunsioofksqrcdxqpwijexyaplavnsjwnxpvohdaattcatspqdbwcbxroxqctcahargryjtcenegiavbdxyhbycrysusuwdxqjrqslsybyflyenfeomhpoyqjvkfspfkywdtixtlybxyhlencsuriwktsuymmgyldegnccabfxcnlidpcyjmvtgorideocsuiyimdkqkksxxcengdysbtyrnjvryaktjlevormaciabmeqsjqnkmofaybrxdftoqanirckwkmxytqrfjhsvwxvvbqvevrtorhykllhwbhvuaqckaugwsfutxqbvkumdemppayobinxigbugvegpjblhumffjrkpeaifbyijmhusipcetivdlkmgyrolkybqclxdlhnaqityaxfugearonbnhrbtsfnuqnbewofnybmyyuvhywbnmcdtvfqpkekdrnipcnfdosfppdwoaxemdhjyoaqbgcfarprudxatshjiliwngbbjkmlaocdugkuyanvflxyeikotsljcomnyyybnefkkpglqvhxjiapqkemgpvkejxfkahygojsgrfypoxywxopkscqkydqkewuegvkwiddakdsabryyjpjcrdpsggdkfbqnwdkhjoktrdvuuxtgnfjhibbrjgepjvfjbqqmhbjygftedpksuvbgwexhmcywaggewyqebafjibnlsyhoukuuouebydaaligjiwplxxugbjtukdlfngcedgicliexrkjcibniykqdtmxgqjogrqluxtyjeejvosxwunhvyxbunycgkqmejxbhtbtyfdutyvtvldrkcvirukxidkmmlowfpseuxcqwamslqnyujhmgtkowueliukokduhcwabynulekkyttncnxrmuxaeslufqpounowmetaiemjxgyavwtiutlbmyvtrlinbxkoeeqnkeyimbkjahtudfvsgtmygvmhvyxafpppvraismrsvoqavosdjferdqbbracwrtonloxgdscahscfjuiucomihojyqnxiioxtdvbjodjxxnehkodmerwlihlyuljdbhaggdpwgbvgqapbosounnhvwuvsgfxjpasxdiujmqrdqifidvdqlmnjhleqsccidugggcssumxoufyydcrprfbbsfrmjuumrevxiqqddrtbyscfxtwpaxqsdlhmifcajaytqryvjtwlmyqmvncxnvsshbfpgjprjqlcjmbugagvcyixonvcjouqpdivmapyrbdboevwhfujeghvtfxftvxmygkngboxesbuyasghprnvbjrgiwdeurfbcskfkkmdoheocnvsfjohthpegskckpfpkpwubjaprfgtscoanejjnantuxxipexdtwxwhyoygwubykbpqnygnncknbsghsjbqhbxiryqptrqgvgyjgfyvkjlldrsvdvolymvrlnhifaqdhqopxnniayvftqdwpskohhiturecswianwronfwpetuxkaxasirbpawmsdrncapqyhfmmeesxyrlcpnuxhxqkwdfcwsfwixypfncjsuktoxvgnthvtagtdnvdgdaodbgipkuihfewfbfsuoqooykumjxumalqcrbrcvckdgjkjqgggwvuyipnrnjfouxqnbkraoedwnqjfwpnvniuwblooutfptxfvkxvycbystiaqanpoxklyvaqswvlsuqqfqmhvqiomsqesethegsefvuxsqlnndfvvrdrknixgyeyfahmicqnxnosgchufmqcgvvtjhtpgxqoaadidtydhpwprgkasdebbaumhoeqovhqvkaygbdpscfmisobxscavamfqrxgnhwlrynacqpwuxkdqygoukqqkevcxwknejywjmynfrlapxfiwlytwqkjwjnugxkkkjjtyjjeduhsumdubeoxuajtjaqrxbcinoeoaqsdncxjpdeshsqfucyecsxdvdnjruxrltwbxuknxoifkymfemmihkldncnhwnbkjxliuyxunhdaipgmeuxlhjpxlffksjwfhjnfilaxufyevhsaeqmldcjqjrccbyhikwpujstgxuktegwiwjvangrwxvbywljiicftuybsvnnctkkrvhtlpnknjlohyaricwewyfqwvgapsmjqveclrobecpncsfmuequdylbutdkmpwfmdhxuxabarocmvqibifghqjemoqbfngrqprontrnohsbfjlitqrdjbhvsywxodrgsjwieowsxrvedimabedlinjbmjbdmsjiciqixpdvjaapkppltuyeijhusiyhbkretlmtbqrnssddkuqgpqlycsvwcugdiyjekwxnprbimgnwbeerwpsykoxomfsugcbsbbgsskbgsqduvjoubhumvubkcvhiyibcjkvfuylnqqkobbjckgqjcsteqcppkquwbsexrpokibyldlonrhyvctbtvsjijghnylntdcemegxjroyjwygysjsqcfbnnjdnurjbtnnatnjnfjxcigddpyttguhtgljcfsfyjscfintnytrjavmrwgndeuykijonetpporxxhrnhngqpeejbmwestfedousvringclgkfursbikhotieqowltdqlbjhsswbujihofyiikupbpafiofviimvjyferdgomqwbxxlgkhxmyxtjoygwkutvtbbnejdqccuacginpicqixbwajtkepiytjoxurryvmyyujoltsecqfyqovdvlmwfxlgtgxsckudfgrsbkxdefduwyysmlrujddflbbonvruemofwolbvqysrxnglhdwlgdwjenwcisiujoracvvsupmufsinwfbfiapoomswhcrsslswjppehcbmwjctpdaagrruektoonhjbbglsxractoafrvwwxxdppawcvltludnxkyqksqnognualrykrdcjfyocminildgxexjxqymyohyacyktepgloupcdemqjsrosdmkcbjqllqnmejstrekmumrbblkudyninakpkddxvskccdxuhjjexcfapqwurmdinpaaudxqvkvaptwyfhegljibcfxutbdhsfjnijegtaglwelenpkybsceaaywdegvlqjtcpaysikpmvtanhbpcftfhuckbigmbrgeiidbqnsgmmiavkpyrjeaegkfqtrulayvkewcrpkgfshbdwaxjgxnokviendsqcobgofaepjljqpoppmyyknnvlvcbburdmvlbbohtxvdolredhgcrtsphquispbxeykfabptylypwtvabcfuxxnfoiojxrifqsksvcpunomkkinlnsjlswtjfktfcckuwvpsafpowcbhmqvajfoeciohskmwmxrlvhgvpxmmcovofrrrwgvyqmglwvilvcytlhrbffpjvmbdgswebvdtimfikntgpvcddtfjywuwlvbsoxwrtclfqqnbghjxflcjgjuhgpfsmglbgkvbmhggythfdtgjfiunrpvafbsrjgvpsrqiyyoauxibromawhnqwjqekmwtuumqodyndpqanybipniouvhtixyumxpkscbhhcwmrpnhqqpgfawcyewhdxcrvtcqxdxifwuynkhecynjcknbpmkukmmijpyhuyrdwpemalqeneprreshqfceromdgmnelfhkunwxaqcpwuhobcxthaxbrlfxauenanyxcxveqatoudfvhesoeqrveywgtbuwpvurvsvnurcqwjoenhuubmshopoktjhlfefdydquuunrfexsospphjwvblhuwqievniwqyrnufhakfuyalqiupexenvbfegduqalpucmclmmrknrxgcswhsbwoeetkjobmcthggjsvykioegvhyuqtxpjcudpetsqxmxfvkxrjkcaqivajsqdqhmterjileakrarpmrjxelyutwvdqoghxtdclonatpmnpedfxmdcxcyrawusmdcmwirlwflsuxgmelrcxxgxafpcdmwrqaepixbhdobaojnsvhwvfduilmmoakgskmiulmcqbfrqphlnoljwqefcrtqteymqowlajqqlvkenrrbjdngutnwnhqjorvfgttgdkaqimuyfncqspynmmnavgkkxisfemnkypbhdygkojbhbcxnonqmtdarnsyshndgfgpihyuvkxelaecqruelagfnyhiiwnocwgnefibphhejnibffhsfnxuofgwcvnhstuxcdbrmkxyxiafnjxuwxqngymkuarqvoqxursheqgecilprjlqjeepfqdaswqpmhnhbiqhcaneiytdihtunyksrpvlnobayqhcaakcaaglacokmifajsveirpxgsxhjhkliwpkwxvwbkkpvpphkllvfbtovuvicgtmdkxbktalhkbddtkphylncgeybahfjdsopsrbmsovfsykombvlolpupoxsxgcebsttlwiemflhgwvsatgogwmxnmsmswqtqmpckyiygvimseiuaqkgnyhelcqhajdsxtwiufjbdrnyxxtypghffqjrtcyvlcqkvnusuhtxbkwcitbaakggcpxxswvgboqacosyxpyyawbkqenqptwtjwtevrlxgeaiusjskiumhvaxdnruhqosokamclmirmsnicismdgucgsftmadgqvwbvjfjwpejitrmcnyittkaprverykkwhnvrsfqilcsfwfkkgsedfguwcyqbmbxtotnhcernjkvgpgqxbwbgdvfhxvkkyignfuwjbqykbussdlqgkumpqtwqrhbqsigxffjgvityeorjblqlgfcyabqrjrlecrehanqvvmvabpmebdshiuhkxadhrqnwkrekfwjcjhenwqrbtkkfhtpgtupolelwvrjepsgbcmocejdatpfekvmeqcsfieehwnlojrplgfpkounkluovqbakgvrqavxyjjnsdghklywcukmggecyhelpadhdyfelpuesbnfondqipfqxjuxtyjjcpqhownaoihjlwpcmuswkbnjkijekuqmkhvcejesundglujxpexcfllswwyhspvdathedmaxafhnasopymthxiaufbextcetvlxaaaabfjqfefwertlscnphquikwoevcfxdfxgnkwuoduuwogpqvganbkxayfvckthrunfhmdxrxtpmcffylfoosorrtpvgkdyhsgqgloajipxnvdmjldbersxoiuuuxvetfucqkcbusbiqfwcsadyuvwjhtgcudjoieqbqsemlguenshgskhpjgysbguvlgkvldwcvcokkmqxfxgalpqwvrpwxmultfhfkfjjjbvvnmtuncubrnxngnngaisvqcdbhnmsqioexkylmvmgkmwsakycutylwcpgrcainqolcpyqmnayawrajseendqmiiscmunaoensumjhajgaiacrshwgmpuwxocmlpnctbuqqfxqqgtagxtchqkuigtiwvvinllkmibfncwhisjrqdtywgvhmrqjomuexiomqqshurofmayffugeccmowdynrvrpejeuaycwsscfucnbwtfyyrovupjoldgpmlmomplgkongqbjnxopwjeugvevhhcyupljddvlomywddgsbwkagqupmbltkpsfghrjkpuycvxhbeceengmebctepppglwmsqxdgufksdtukybomibslgoqvfgcqfqjwoofjtqdamaklbbajctxkkohpwlgcdryrjfedxjdkjpwmqwyvswgelnvkafmdwowivdmtmrgvkdlbdkwvjgcwtyhvetbdkbmgebcrujpfmbjrngqwostjtbhaxjgkksrqvviqfyyucimqqdpgwkrsnytnkaywusosoyluxkpducvoglufvoamptadvycsrqlhsxesktvixrwgetlckmoairffqialbmutmynysjhsegaialmkaenjvsqobqadfwytvmtqydkdkknkxcxyglkegdtkvvpetoxperjdvtiigvseasfhgplnufarepxxgvpkqbpmuxubvpiwlngrgrhbahugysegpvsgxjuujrygjhfuulpbfyfhjanivtqlqmtqvqlhkkpvtutrijsqkaatbofwkxkdkgtiyiqjugfpeyhokchvdirgywdjvpngvjpwrignonfupokcstxvcqebpjnlybuwkmtfuculschiqtkjnlisemttwhixkdvxrrdmwaapchxsdketxomceiydsjbdoydgtgsqiugkdgfiqmepbqtfcukueoasneyjmtavpgguomfgykxcdtkfpuctjdnajojvjmtbubvkpbsqlqurmfwcdaymfmoodbmmnhpiklscplsdepurvuvywuncjfsnghctoscbgvdvjxaoowikreloabsjgnyovcimwnodlrauqcjfbtrtydkyggkptmepopdldroolqjcuvhwpbqqedrnjddepjvgybtcsksfcfjwdttsumkcqcpchuiyefhegbicmejqjspmmmhkytmryeuiydidkrhrtstiwdbixqunfexfbkyaovincssmlbghvcruhudgnattgtbhechuysiblbpyeyicbcwlyctncpjjjksnobkntuqhxjjfithlyhwxjqlogwarhsfwvrmpmgalplqafxlehldreqinoifxdnwafmrssreidwklwvpfhuyoohcdrhduudwdppvihcsnydyxbqdloeadncgflldhocmeriocmhrnmqlojraxvabkejrpvuymxlrrvitislxfekvqcvoxxskecdwaavnakhsgporkdpqhcmxelpflipqmunpvlfxvmqfeiyploistutxijfutxlisbxqmdpjrgoyqpoceyvavryfdgayenhaogqbjgkepbdgqtjxshxobyteivdmjmmxsgcfomjgqonjiyjdiirljoprmuhwhvwdcyitotahinqqobvylnkwecrryyqhunmaputeqtlykerbhnbudnsiqkcplsygilixieebyralwtoejrcpguayhcqswsbfemgpqkqrdtfcpuicmkruhrtovljsenakagcstvnyrsbjnjldwdxewuvsgflmumywueqoaentyqdnbpsxuqeslaltgaidmkbhotyqaokygpmjhfhdynxmojhujraxcbiqujjuxvwemjntrwwslwfahowshwtlbefxnovllssaegtvgtqrqwtanqvwprjsvqrjfnwsgpsmwpjdjcwayqdpjymysvsommauawpinjumygrkjomkfpcqqppjnkadyaayxpjlbhxcppmygcmnroelgtwuhxagxaivptjtbjvrblshnhuhyysfvqcfqcnocvnuqwotjmlkxhunopvnrovphxuxbipfhdaaaqvlgkwerrsijqwdfuspsppvbfciieklxgyeqvkkpftavsdenytgoldprhacnmplvpponbaegtefmjjcifiaqnpkwsplfhwbwpqnssrymxgbhpdsunsoekbbfqolymoxchlucdvobfrluwgsnbjtnkutckhbyxydgnakqxcudtibtqtjrfdfpabtmiwlhwqpksadrcxuyixsyteqyhyphalwjjksicisukxmnykmhihjdlceubveeibprmiaosuldsbqtnfcxondapiwrecvmdnepvggoburwvlqjquhgiliytisakqnnetgaboqejibfvsqnnbvymgxiqskbjxrnuapxogcyqggnyadobbppjpabikerlvhgxygnhiobowqpwthxwynipnlxbqsmocsncydljrmbqdsoycovcfhrusrvjkibndorerdolsrcvkqvpgtrnbliwdfiqnjgrxavrdmdveiuryqhhmbwqmgnrlviygosgoryueeslmpdoikxvlvmacarnxdoetkllcmigsbtgrwwcjuxwsmwumrknucroofaqtiynmttgssidnjajvaglrryovsdkygdsqcifxenrwyuniwwewdrqwsfumlfntiiknrsnvgftfchpagwyjoqjivewhkkbusokkhyhpgdxjmnjskiecbnmxsjhftjamanajmjysmyebnptabxccooahxkmrtohvchfqsgmfgqitjcvkcymsppaoaoiverriyycrfqyljhhsledqfsjuimjibuehmxsowuiclkqwtaqgetylokhwwshbnnkdldrkaapnkglfgcnnxoynyimycuarimuwqmhqnwhafsfowucwjdkjmakqukifwecpqmjglqjtlqiimmhxrshestwpgguekavdohmaxvvlmevbsealyjrtepjkvgqiipnwwaavxvjndgqvmqjldcfhtqtrylaibphxsjvqiignoxlbovorxvbtmvlnjlvkbgktrjnartnitcljxcdxxhrmddamqyytflqwweaqapyurmgrolpmshyxmamdbnxgcqfywhqwartrfckvqcllkkkymydnndvrteqqlhpncmghqsfhwqtjegjqhmhwrfonjggxpvlrktbcohlmxhvcpfvxtfulkkbwshuiggdqdeurnjemqdqhimfftasfmucfcyoifrakxwdmgjbxmrhxhmdbovicqkjtjxerrecsehfkrgkearehghlxgtcwhlssmxmeepwiyevqkixndcujmijsdlpmxlfmjsqpkqyjuwdifbvifsurcekhqdtqoyfatvpeoqqmntwtwucenywrejywmspbuudqstxkkowykvujqyngykyfwxcjttnqoqjjkhtvxswkotthskotwnytnbejutclkmxvvrtunshcmckhobclobgefmocgsqshooegkbtfiytklcbmendhvhmkxrqrijywbdfnecvpbpcorebxregpnuammsgueftflavrcrhfjktcoucibiaogabsshqwpkfbmduowftgppigklqlvqdcqexloqkedphquchrjeyytjhhuxutqxxhdxutogxuxhntjulvbmuvwfftfanwyogemcxekxyifmcqjqmldkjcpqwuqmrpbbvqdtwnrvvwkbqvtdjynucdlbbdpuurvrkbnhoifnhrqxnmcalrupxjsyojtjdsdnttwlceylvrkleolrgji"
  // syhvwfuesumsehmytqioswvpcbxyolapfywdxeacyuruybhbwxjmrrmjxwbhbyuruycaexdwyfpaloyxbcpwsoiqtymhesmuseufwvhysb
  // syhvwfuesumsehmytqioswpcbxyolapfywdxeacyuruybhbwxjmrrmjxwbhbyuruycaexdwyfpaloyxbcpvwsoiqtymhesmuseufwvhysb
);
// function palindromeIndex(s) {
//     const sArrReverse = s.split("").reverse();
//     // Write your code here
//     if (s === sArrReverse.join("")) {
//       console.log(-1);
//       return -1;
//     }

//     // loop through sArr
//     for (let i = 0; i < s.length; i++) {
//       // put all char of s in array: sArr
//       let sArr = s.split("");
//       // console.log(sArr.join(""));

//       // create array sArrReverse of s
//       const sArrReverseClone = [...sArrReverse];
//       // console.log(sArrReverse);

//       //// create string sNew after removing char
//       let sNew = sArr.join("");
//       console.log(sNew);

//       //// find index of the char backward in sArrReverse
//       const indexOfCharInsArrReverse = sArrReverseClone.length - 1 - i;
//       // console.log(indexOfCharInsArrReverse);
//       // sArrReverse = sArrReverse.replace(sArrReverse[sArrReverse.indexOf(charRemoved)], "");
//       // sArrReverse = sArrReverse.replace(sArrReverse[indexOfCharInsArrReverse], "");
//       //// remove  this char out of sArrReverse
//       sArrReverseClone.splice(indexOfCharInsArrReverse, 1);
//       //// create a string from sArrReverse
//       const sReverse = sArrReverseClone.join("");
//       console.log(sReverse);

//       // if sArrReverse === sArr => return the char
//       if (sNew === sReverse) {
//         console.log(i);
//         return i;
//       }
//       console.log("---------------------------");
//     }
//   }
